### ISSUE TITLE
home is not defined

### ISSUE THREAD

**Issue by goldenxp** [cinqmarsmedia/Trade-Bots-Algorithmic-Trading-Game#3]
Unsure why this occurs but basically there's a flicker of errors and the page reloads to 
```
Runtime Error
home is not defined
Stack
ReferenceError: home is not defined
    at http://localhost:8100/:1816:65
```

**Comment by ccj242** [comment]
You're right, I just tried it on windows and there's an issue, I had only tested on linux / osx.  I'll work on it and fix it as soon as I can. Sorry about that!

**Comment by ccj242** [comment]
This is driving me absolutely bananas. I cannot for the life of me figure out why it's not working on windows. I do have a script that uses a unix tool "find" that is fixed by using git bash. "npm start" works best as the build command btw. I will continue working on this.

**Comment by ccj242** [comment]
Finally fixed in latest commit, I just changed "declare const d3" to "let d3" and that resolved all typescript errors I was able to reproduce on windows. Thank again.
