### ISSUE TITLE
npm ci post install warn and typescript errors - WSL

### ISSUE THREAD

**Issue by adyos7498** [cinqmarsmedia/Trade-Bots-Algorithmic-Trading-Game#4]
Done on WSL with Ubuntu installed, and is probably just my oversight, because im not knowlegible about node.js too much.

command line output : https://text.is/KV34 - Second to last line (warn), failed post install command, I think, and syntax looking typescript errors in npm start (maybe wrong typescript version, idk)

I had some builds failing before, fixed the problems I knew how to fix. For this build, I deleted the code directory and extracted it fresh from downloaded code .zip, but before I switched to WSL (after learning that windowns may not work), i got similar or same looking errors.

Once again, total noob, maybe its a trivial thing, and thanks for reading this horrificly written piece of github issue regardless :)

**Comment by ccj242** [comment]
Hey! Sorry you're having issues - the windows problem was fixed awhile ago, would you mind giving it a try without WSL? I haven't tried in WSL but I have on my ubuntu machine and everything was pretty seamless. If you can't get it working on windows I'll try to recreate the issue and debug further. Thanks!

**Comment by ccj242** [comment]
accidentally marked as closed, sorry!

**Comment by adyos7498** [comment]
Ran it via nvm-windows and git bash, npm ci went errorless, and npm start thrown the same errors as on WSL (I think) :
https://text.is/P21M
Output on web looks like this, but its probably the same errors (close does nothing, and it was the same on WSL):
![image](https://github.com/cinqmarsmedia/Trade-Bots-Algorithmic-Trading-Game/assets/44033699/99907684-02e6-43b1-b5f0-6780dfb80f64)
OS is Windows 10 64 bit, if it matters

**Comment by adyos7498** [comment]
Also, noticed that version strings say that the open sourced version of the game is 1.3.4, dont know if its in error

**Comment by adyos7498** [comment]
Im now 99% sure that the problem is from the postinstall script: windows (git bash) does not log command errors and WSL ubuntu just WARNs trade-bots@1.3.4~postinstall: cannot run in (the command). 
Kernelgreen managed to fix the find command by removing -E in #5 , on git bash and even on ubuntu WSL, find doesent have a -rem option. 

OOPS, while getting full output of the postinstall script (in WSL), i ran
`patch-package && rm -rf node_modules/rete/types || true && rm -rf node_modules/@types/node || true && rm -rf node_modules/rete-connection-plugin/types || true && rm -rf node_modules/rete-dock-plugin/types || true  && rm node_modules/litegraph.js/src/litegraph.d.ts || true && rm node_modules/@baklavajs/plugin-renderer-vue/dist/baklavajs-plugin-renderer-vue/src/components/Editor.vue.d.ts || true && find . -type f -regex '.*vue-.*.d.ts' -delete && rm -rf node_modules/@types/yargs && rm node_modules/fast-sort/dist/sort.d.ts` 
in base folder manually just to see if any commands are missing and none came up, then npm started just for fun and it just casually started.


So, the problem is in the postinstall script and running it manually worked(t, if somebody in the future has similar problems as me  (or Kernelgreen) and is/can build on WSL, I will retry the build process and document it properly. For now what i remember doing is :

1. Changes before build: remove the -E from the find statement on line 19 of package.json (the same is then done in the manually ran postinstall script)
1.2 In \src\pages\home, duplicate Logs.html and lowercase the copy (Does not need to be done when building on non linux systems (These two things discovered by Kernelgreen.
2. Get WSL with Ubuntu
3. Install nvm with NPM 10.24.1
4. Install either Python 2 or both 2 and 3, i think some dependency requires specificly 2 (tries to print without brackets)
5. Run sudo npm ci. If there are no errors, or its just a sneaky WARN for the postinstall script, its OK, if there are errors, i forgot about a step probably
6. Run the post install command manually. Output looks like this, maybe with the last two lines missing depending on if the postinstall ran in npm ci worked :

patch-package 6.5.1
Applying patches...
@baklavajs/core@1.9.1 ✔
@ionic/app-scripts@3.2.4 ✔
ionic-tooltips@3.1.0 ✔
rm: cannot remove 'node_modules/litegraph.js/src/litegraph.d.ts': No such file or directory
rm: cannot remove 'node_modules/@baklavajs/plugin-renderer-vue/dist/baklavajs-plugin-renderer-vue/src/components/Editor.vue.d.ts': No such file or directory

7. npm start and hope for yellow warns, not red errors

And also, will buy the game off steam soon, happy that the sources are available

**Comment by ccj242** [comment]
Wow, thank you so much for sharing how you got it to work! I'm sure this is going to help a lot of people. Thanks again!
